version: '3'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - cbot-data:/app/data
    restart: always
    container_name: cbot-kurulum-asistani

volumes:
  cbot-data: